name: Check Markdown links

on:
   workflow_dispatch:

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      continue-on-error: true
      with:
          config-file: '.github/workflows/markdown-links.config.json'
          folder-path: './apps/devportal/data/markdown'
