name: deploy website
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
  deploy:
    #if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: start deployment
        uses: bobheadxi/deployments@v0.4.3
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: Production
      # - uses: actions/checkout@v2
      # - uses: amondnet/vercel-action@v20
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
      #     vercel-args: '--prod' #Optional
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  #Required
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} #Required 
      #     scope: ${{ secrets.VERCEL_ORG_ID}}
      #     working-directory: ./
      - name: update deployment status
        uses: bobheadxi/deployments@v0.4.3
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}